POST http://127.0.0.1:8000/games/target-scores/ HTTP/1.1
Content-Type: application/json

{
  "time_elapsed": "115.999000",
  "clicks": 41,
  "targets": 30, 
  "user": 1
}

###
GET http://127.0.0.1:8000/games/target-scores/ HTTP/1.1

###
POST http://127.0.0.1:8000/register/ HTTP/1.1
Content-Type: application/json

{
  "username": "test_user002",
  "email": "test_user002@email.com",
  "password": "test_password002",
}

###
POST http://127.0.0.1:8000/api/token/ HTTP/1.1
Content-Type: application/json

{
  "username": "Will",
  "password": "devpassword"
}