# Generated by Django 6.0 on 2026-01-06 22:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TargetScore',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time_elapsed', models.DurationField()),
                ('clicks', models.IntegerField()),
                ('targets', models.IntegerField()),
            ],
        ),
    ]
