# Generated by Django 6.0 on 2026-02-22 02:56

import django.contrib.postgres.fields
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='targetscore',
            name='clicks',
            field=models.PositiveSmallIntegerField(),
        ),
        migrations.AlterField(
            model_name='targetscore',
            name='targets',
            field=models.PositiveSmallIntegerField(),
        ),
        migrations.CreateModel(
            name='ReactionScore',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reaction_times', django.contrib.postgres.fields.ArrayField(base_field=models.PositiveSmallIntegerField())),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
