# Generated by Django 6.0 on 2026-02-22 03:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0003_alter_targetscore_clicks_alter_targetscore_targets_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TypingScore',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('wpm', models.DecimalField(decimal_places=1, max_digits=4)),
                ('accuracy', models.DecimalField(decimal_places=1, max_digits=4)),
                ('raw_wpm', models.DecimalField(decimal_places=1, max_digits=4)),
                ('time_mode', models.PositiveSmallIntegerField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
