# Generated by Django 6.0 on 2026-02-23 18:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0004_typingscore'),
    ]

    operations = [
        migrations.AlterField(
            model_name='typingscore',
            name='raw_wpm',
            field=models.PositiveSmallIntegerField(),
        ),
        migrations.AlterField(
            model_name='typingscore',
            name='wpm',
            field=models.PositiveSmallIntegerField(),
        ),
    ]
